version: '3.8'

networks:
  fsharer:

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: files
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./psql-init:/docker-entrypoint-initdb.d:ro
    networks:
      - fsharer

  backend:
    build:
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./storage:/app/storage
    networks:
      - fsharer
